Repository jfmartinz/ResourceHub, pull requests merged in 2024-05, with the labels that each got.

#129 Update README.md
  README.md
Labels: gssoc, Level 1

#121 Web Development - Design patterns/Solid principles & best practices
  Web Development/README.md
Labels: gssoc, Level 1

#136 Web Development - HTML, CSS and JavaScript courses
  Web Development/README.md
Labels: gssoc, Level 1

#146 Web development - Web Design for Everybody: Basics of Web Development & Coding Specialization & Front-End Development
  UI-UX Design/README.md
  Web Development/README.md
Labels: gssoc, Level 1

#155 Correted Typos mistakes in feature.yml
  .github/ISSUE_TEMPLATE/feature.yml
Labels: gssoc, Level 1

#157 Added Roadmaps for Web Development
  Web Development/README.md
Labels: gssoc, Level 2

#158 Update README.md
  Web Development/README.md
Labels: gssoc, Level 1

#185 Added UI/UX Design challenges under README.md
  UI-UX Design/README.md
Labels: gssoc, Level2

#180 Changes made
  UI-UX Design/README.md
Labels: gssoc, level1

#255 Update README.md
  Web Development/README.md
Labels: gssoc, level1

#284 Rename README.MD to README.md
  Open Source Development/README.md
Labels: gssoc, level1

#300 ! Here is your website
  website/README.md
  website/app.js
  website/content-display.html
  website/index.html
  website/style.css
Labels: gssoc, level3

#309 Added "Java Development" and "Java" Resources
  Programming Languages/Java.md
Labels: gssoc, level3

#315 Fixed bugs
  App Development/readme.md
  DevOps/readme.md
Labels: level1

#341 Added some more open source events
  Open Source Development/readme.md
Labels: gssoc, level1

#337 Issue number: #1324 Adding roadmaps
  App Development/readme.md
  Machine learning/readme.md
  Web Development/readme.md
Labels: gssoc, level1

#329 Fixing documentation bugs in ds, dbms & ui/ux
  DBMS (Database)/readme.md
  Data Science/readme.md
  UI-UX Design/readme.md
  Web Development/readme.md
Labels: gssoc, level1

#335 Modified Courses section in App Development
  App Development/readme.md
Labels: gssoc, level1

#349 Added Machine Learning interview preparation resources
  Machine learning/readme.md
Labels: gssoc, level1

#350 Added Challenges section to data science resources
  Data Science/readme.md
Labels: gssoc, level2

#356 DBMS - GitHub Repositories
  DBMS (Database)/readme.md
  UI-UX Design/readme.md
Labels: gssoc, level1

#357 Python Development resources added
  Programming Languages/Python/readme.md
  README.md
Labels: gssoc, level3

#384 JavaScript - Added Additional Resources
  Programming Languages/JavaScript/readme.md
  Programming Languages/Python/readme.md
Labels: gssoc, level1

#398 Programming Languages - "C++" Complete Resources
  Programming Languages/C++/readme.md
  Programming Languages/JavaScript/readme.md
Labels: gssoc, level3

#404 All Headers Updated in App Dev Category
  App Development/readme.md
Labels: gssoc, level1

#406 added a link under YouTube Channel in web development file
  Web Development/readme.md
Labels: gssoc, level1

#423 Programming Languages - "C Language" Resources
  Programming Languages/C/readme.md
Labels: gssoc, level3

#327 Open Source Development - Bitbucket
  Open Source Development/readme.md
Labels: gssoc, level1

#328 Added search bar and separate programing language folder
  C++/readme.md
  Java/readme.md
  JavaScript/readme.md
  Python/readme.md
  website/app.js
  website/index.html
Labels: gssoc, level1

#427 Updated readme.md
  Machine learning/readme.md
Labels: gssoc, level1

#429 DevOps - YouTube Playlists
  DevOps/readme.md
Labels: gssoc, level1

#428 Stone-paper-scissor-game
  Web Development/readme.md
Labels: gssoc, level1

#436 Added python resource
  Python/readme.md
Labels: gssoc, level1

#437 Updated "Programming Language" folder structure and Made Additions in "R programming"
  Programming Languages/C++/readme.md
  Programming Languages/Java/readme.md
  Programming Languages/JavaScript/readme.md
  Programming Languages/Python/readme.md
  Programming Languages/R/readme.md
Labels: gssoc, level2

#453 Programming Languages - "TypeScript Resources"
  Programming Languages/TypeScript/readme.md
Labels: gssoc, level3

#438 Machine Learning - geeks-for-geeks Seaborn library
  Machine learning/readme.md
Labels: gssoc, level1

#449 Add Card Blackjack game
  Web Development/readme.md
Labels: gssoc, level1

#441 Programming Languages - "PHP Language" Resources
  Programming Languages/PHP/readme.md
Labels: gssoc, level3

#472 added loading animation and error fetch message
  website/app.js
  website/style.css
Labels: gssoc, level2

#482 Added descriptions in DevOps
  DevOps/readme.md
Labels: gssoc, level1

#479 Fixed token security issues
  .gitignore
  website/.gitignore
  website/README.md
  website/app.js
  website/package-lock.json
  website/package.json
  website/server.js
Labels: gssoc, level3

#470 Data Science section formatting done
  Data Science/readme.md
Labels: gssoc, level1

#478 Programming Languages - "C# Programming Language" Resources
  Programming Languages/C#/readme.md
Labels: gssoc, level3

#412 Update README.md in Web development with examples of Full Stack Technologies #198 issue
  Web Development/readme.md
Labels: gssoc, level2

#454 Python - online interpreters/compilters
  Data Science/readme.md
  Programming Languages/Python/readme.md
Labels: gssoc, level1

#484 Web3 - Tutorial or Courses
  Web3/readme.md
Labels: gssoc, level1

#476 Updated "Table Formats" of Each "programming Language"
  Programming Languages/C++/readme.md
  Programming Languages/C/readme.md
  Programming Languages/Java/readme.md
  Programming Languages/JavaScript/readme.md
  Programming Languages/Python/readme.md
  Programming Languages/R/readme.md
  Programming Languages/TypeScript/readme.md
Labels: gssoc, level2

#489 update js
  website/app.js
Labels: gssoc, level1

#497 Added the feature to auto comment on a new issue creation
  .github/workflows/auto-comment-on-issue.yml
Labels: gssoc, level2

#473 Added Github section in Devops resources
  DevOps/readme.md
Labels: gssoc, level1

#477 [#440 ISSUE SOLVED] Update content-display.html Making code visible in dark mode .
  website/content-display.html
Labels: gssoc, level1

#504 change C# to C(sharp)
  Programming Languages/C(sharp)/readme.md
Labels: gssoc, level1

#507 impliment programing language pagination
  website/app.js
Labels: gssoc, level3

#517 Flappy Bird game
  Web Development/readme.md
Labels: gssoc, level1

#514 C# Headings updated
  Programming Languages/C(sharp)/readme.md
Labels: gssoc, level1

#492 Programming Languages - NodeJs Complete Resources
  Programming Languages/NodeJs/readme.md
Labels: gssoc, level3

#521 Python section formatting
  Programming Languages/Python/readme.md
Labels: gssoc, level1

#532 google chrome dinosaur Game
  Web Development/readme.md
Labels: gssoc, level1

#539 added github repository for data science
  Data Science/readme.md
Labels: gssoc, level1

#546 App Development - YouTube Playlists
  App Development/readme.md
Labels: gssoc, level1

#536 Programming Languages - "AngularJs" Complete Resources
  Programming Languages/AngularJS/readme.md
Labels: gssoc, level3

#464 Updated autocomment.yaml
  .github/workflows/autocomment.yaml
Labels: gssoc, level2

#585 Fixes #529 Bug Fixing - Toggle Light Mode/Dark Mode in the Home Page of the website.
  website/app.js
  website/index.html
  website/mainstyle.css
Labels: gssoc, level2

#551 Added python resource
  Programming Languages/Python/readme.md
Labels: gssoc, level1

#575 Issue Reminders
  .github/workflows/issue-reminder.yml
Labels: gssoc, level1

#568 Frontend Development - All Resources
  README.md
  Web Development/Frontend Development/readme.md
Labels: gssoc, level2

#618 Favicon Added
  website/index.html
Labels: gssoc, level1

#617 Fixed table formatting bug
  Programming Languages/C/readme.md
Labels: gssoc, level1

#622 NavBar alignment
  website/index.html
  website/mainstyle.css
  website/style.css
Labels: gssoc, level2

#593 Data Science - Projects
  Data Science/readme.md
Labels: gssoc, level1

#596 ADDED QR Code Generator
  Web Development/Frontend Development/readme.md
Labels: gssoc, level1

#600 Dark mode is enabled for learning content also.
  website/content-display.html
  website/mainstyle.css
Labels: gssoc, level2

#611 Feature Enhancement- Displaying "No Results" found if resource not found
  website/index.html
  website/mainapp.js
  website/mainstyle.css
Labels: gssoc, level2

#666 Added contributor section
  website/contibuters.js
  website/index.html
  website/mainstyle.css
Labels: gssoc, level3
