Repository jfmartinz/ResourceHub, pull requests merged in 2024-06, with the labels that each got.

#673 fixed no results
  website/index.html
  website/mainapp.js
Labels: gssoc, level2

#711 Add-RainbowKit library in web 3
  Web3/readme.md
Labels: gssoc, level1

#685 Made the logo visible in both modes #659 solved
  website/index.html
  website/mainstyle.css
Labels: gssoc, level1

#684 Added SQL projects
  DBMS (Database)/readme.md
Labels: gssoc, level1

#681 Website Feature- Enhance Testimonial Section with Flip Card Styling
  website/index.html
  website/input.css
  website/mainstyle.css
  website/package-lock.json
Labels: gssoc, level2

#630 Fixing Bug- learning section & Card Text Overflow.
  website/mainstyle.css
Labels: gssoc, level1

#668 Web development - CSS of Navbar for light theme visibility
  website/mainstyle.css
Labels: gssoc, level1

#665 Category - Machine Learning & Algorithms,Dataset
  Machine learning/readme.md
Labels: gssoc, level1

#663 Data Structures and Algorithms (DSA)-Adding DSA Resources
  Data Structures and Algorithm (DSA)/readme.md
Labels: gssoc, level3

#661 Implemented Multilingual Support (Issue #632)
  website/index.html
Labels: gssoc, level3

#655 NAVBAR : Fixed hamburger menu also showing in large devices
  website/mainstyle.css
Labels: gssoc, level1

#628 Add Appshots and Godly to UI-UX Design Inspiration
  UI-UX Design/readme.md
Labels: gssoc, level1

#626 Updated formatting of Web3
  Web3/readme.md
Labels: gssoc, level1

#627 Programming Languages - Additional Resources for "TypeScript"
  Programming Languages/TypeScript/readme.md
Labels: gssoc, level1

#447 added tic tac toe game in java
  Programming Languages/Java/readme.md
Labels: gssoc, level1

#439 Data science - Udemy
  Data Science/readme.md
Labels: gssoc, level1

#360 [FEATURE]- Improve 404 Error page #359
  Error.html
  error_styles.css
Labels: gssoc, level2

#670 Programming Languages - "ExpressJs" Complete Resources
  Programming Languages/AngularJS/readme.md
  Programming Languages/ExpressJs/readme.md
Labels: gssoc, level3

#699 Scroll to top button added
  website/index.html
  website/mainapp.js
  website/mainstyle.css
Labels: gssoc, level2

#595 Web development - About Page Updated
  package-lock.json
  website/about.css
  website/about.html
Labels: gssoc, level1

#560 Linux Development resources Added
  Linux Development/readme.md
  README.md
Labels: gssoc, level3

#603 Scroll Bar update
  website/mainapp.js
  website/mainstyle.css
Labels: gssoc, level1

#801 Fixed 404 error page
  Programming Languages/C/readme.md
Labels: gssoc, level1

#808 Add-Wagmi library in web 3
  Web3/readme.md
Labels: gssoc, level1

#815 C++ formatting done
  Programming Languages/C++/readme.md
Labels: gssoc, level1

#814 C Sharp formatting done
  Programming Languages/C(sharp)/readme.md
Labels: gssoc, level1

#834 ExpressJS formatting done
  Programming Languages/ExpressJs/readme.md
Labels: gssoc, level1

#835 Go language Formatting done
  Programming Languages/Go/readme.md
Labels: gssoc, level1

#838 Turned off text selection in website
  website/about.css
  website/input.css
  website/style.css
Labels: gssoc, level1

#823 added sql interview questions
  DBMS (Database)/readme.md
Labels: gssoc, level1

#820 Programming Languages - "PERL" Complete Resources
  Programming Languages/Perl/readme.md
Labels: gssoc, level3

#818 computer networks
  Computer Networks/readme.md
Labels: gssoc, level3

#812 Bug - Text color
  website/mainstyle.css
Labels: gssoc, level1

#822 Programming Languages - "Ruby" Complete Resources
  Programming Languages/Ruby/readme.md
Labels: gssoc, level3

#816 C language Formatting done
  Programming Languages/C/readme.md
Labels: gssoc, level1

#800 Navbar dark mode toggle button issue fixed
  website/content-display.html
  website/mainstyle.css
Labels: gssoc, level1

#856 Added DSA resource
  Data Structures and Algorithm (DSA)/readme.md
Labels: gssoc, level1

#858 Added Web3 Interview Resources
  Web3/readme.md
Labels: gssoc, level1

#882 Resources template added
  .github/ISSUE_TEMPLATE/resource.yml
Labels: gssoc, level1

#891 Programming Languages - Additional "Python" Resources
  Programming Languages/Python/readme.md
Labels: gssoc, level1

#898 Data science - Free Books
  Data Science/readme.md
  Programming Languages/React JS/readme.md
Labels: gssoc, level1

#857 Operating System resources Added
  Operating System (OS)/readme.md
Labels: gssoc, level3

#860 "Swift" Resources Added
  Programming Languages/Go/readme.md
  Programming Languages/Swift/readme.md
Labels: gssoc, level3

#901 Machine learning - YouTube Playlist
  Machine learning/readme.md
Labels: gssoc, level1

#900 Documenation Template Added
  .github/ISSUE_TEMPLATE/documentationbug.yml
Labels: gssoc, level1

#802 Added the Gssoc banner
  README.md
Labels: gssoc, level1

#825 Programming Languages-Adding Resources in different programming languages
  Programming Languages/C++/readme.md
  Programming Languages/C/readme.md
  Programming Languages/Java/readme.md
  Programming Languages/JavaScript/readme.md
  Programming Languages/Python/readme.md
Labels: gssoc, level1

#903 DevOps - Paid Books
  DevOps/readme.md
Labels: gssoc, level1

#909 Programming Languages - "Prolog" Resources.
  Programming Languages/Prolog/readme.md
Labels: gssoc, level3

#752 Programming Language - Multiple "Additional Resources for Rust"
  Programming Languages/Rust/readme.md
Labels: gssoc, level1

#846 Add OpenCV Flappy Bird Game
  Flappy_Bird/bird_sprite.png
  Flappy_Bird/canonical_face_model_uv_visualization.png
  Flappy_Bird/gitignore
  Flappy_Bird/idea/FlappyBirdCV.iml
  Flappy_Bird/idea/IncpectionProfiles/profiles_settings.xml
  Flappy_Bird/idea/misc.xml
  Flappy_Bird/idea/modules.xml
  Flappy_Bird/idea/vcs.xml
  Flappy_Bird/main.py
  Flappy_Bird/pipe_sprite_single.png
Labels: gssoc, level3

#911 ADDED LINKS FOR NAVIGATION
  README.md
Labels: gssoc, level1

#904 Added Preview and Production Pipelines
  .github/workflows/preview.yaml
  .github/workflows/production.yaml
Labels: gssoc, level3

#939 Kotlin Language formatting
  Programming Languages/Kotlin/readme.md
Labels: gssoc, level1

#938 JavaScript formatting done
  Programming Languages/JavaScript/readme.md
Labels: gssoc, level1

#949 Programming Languages - Added "Cheatsheets" for "React.js, Node.js and Vue.js"
  Programming Languages/NodeJs/readme.md
  Programming Languages/React JS/readme.md
  Programming Languages/VueJs/readme.md
Labels: gssoc, level1

#933 Computer Networks Resource - Coursera
  Computer Networks/readme.md
Labels: gssoc, level1

#932 Linux Development Resource - NDG Linux Unhatched
  Linux Development/readme.md
Labels: gssoc, level1

#945 Decentralize Google Drive Project
  Web3/readme.md
Labels: gssoc, level1

#931 Computer Networks - Added "Network Implementations"resources
  Computer Networks/readme.md
Labels: gssoc, level1

#925 added core java interview questions
  Programming Languages/Java/readme.md
Labels: gssoc, level1

#924 Programming Languages - "SQL" Resources
  Programming Languages/SQL/readme.md
Labels: gssoc, level3

#908 Added websites -C programming
  Programming Languages/C/readme.md
Labels: gssoc, level1

#962 Update README.md
  README.md
Labels: gssoc, level1

#986 Programming Languages - "XML" Complete Resources
  Programming Languages/XML/readme.md
Labels: gssoc, level3

#985 Added coding platform for DSA
  Data Structures and Algorithm (DSA)/readme.md
Labels: gssoc, level1

#976 added dsa roadmap
  Data Structures and Algorithm (DSA)/readme.md
Labels: gssoc, level1

#971 Computer Networks and Operting System(OS)-Added OS and Computer Networks resources
  Computer Networks/readme.md
  Operating System (OS)/readme.md
Labels: gssoc, level1

#969 Programming Languages - "Elixir" Complete Resources
  Programming Languages/Elixir/README.md
Labels: gssoc, level3

#966 Added App Development Interview Resources.
  App Development/readme.md
Labels: gssoc, level1

#947 DevOps - Added "Complete New Resources + Re-Formatting"
  DevOps/readme.md
Labels: gssoc, level3

#941 NodeJS formatting done
  Programming Languages/NodeJs/readme.md
Labels: gssoc, level1

#987 Added Machine Learning Roadmap
  Machine learning/readme.md
Labels: gssoc, level1

#972 Computer Networks - Added "TCP/IP Protocols"
  Computer Networks/readme.md
Labels: gssoc, level1

#989 Linux Development-Added Linux Courses and Repositories
  Linux Development/readme.md
Labels: gssoc, level1

#974 Programming Languages - "Julia" Complete Resources
  Programming Languages/Julia/readme.md
Labels: gssoc, level3

#1001 Programming Languages - Added F# Complete Resources
  Programming Languages/F#/readme.md
Labels: gssoc, level3

#914 Added Artificial Intelligence Resource
  Artificial Intelligence/readme.md
Labels: gssoc, level2

#1002 Programming Languages - "Haskell" Complete Resources
  Programming Languages/Haskell/readme.md
Labels: gssoc, level3

#1004 Linux Development - Added "Command Line and Bash Programming" Resources
  Linux Development/readme.md
Labels: gssoc, level1

#1000 Add Web 3.0 Amazon Clone
  Web Development/readme.md
  Web3/readme.md
Labels: gssoc, level1

#980 Game Development Resources Added
  Game Development/readme.md
  README.md
Labels: gssoc, level3

#997 Add labels
  .github/workflows/auto-label.yml
Labels: gssoc, level2

#1012 Update readme.md
  Operating System (OS)/readme.md
Labels: gssoc, level1

#1023 Added Python CheatSheet
  Programming Languages/Python/readme.md
Labels: gssoc, level1

#1020 Programming Languages - Added "LaTeX" Complete Resources
  Programming Languages/LaTex/readme.md
Labels: gssoc, level3

#1033 New homepage added
  new-website/assets/homeparticles.json
  new-website/home.js
  new-website/index.html
  new-website/input.css
  new-website/package-lock.json
  new-website/package.json
  new-website/particles.js
  new-website/style.css
  new-website/tailwind.config.js
Labels: gssoc, level3

#1044 Latex formatting
  Programming Languages/LaTex/readme.md
Labels: gssoc, level1

#940 MATLAB formatting done
  Programming Languages/MATLAB/readme.md
Labels: gssoc, level1

#1048 Added new Project in Front end Development
  Web Development/Frontend Development/readme.md
Labels: gssoc, level1

#1011 F# formatting done
  Programming Languages/F#/readme.md
Labels: gssoc, level1

#1047 Readme updated with new programming langauges
  README.md
Labels: gssoc, level1

#1057 Added New Project
  Web Development/Frontend Development/readme.md
Labels: gssoc, level1

#1079 [Resource]- Cybersecurity-Complete Resources ADDED
  Cybersecurity/readme.md
Labels: gssoc, level2

#875 Added Chrome Extensions Tutorial
  Web Development/Frontend Development/readme.md
Labels: gssoc, level1

#1030 added OS Interview Section
  Operating System (OS)/readme.md
Labels: gssoc, level1

#937 Programming Languages - Added "Java, JavaScript and Python Design Patterns" resources
  Programming Languages/Java/readme.md
  Programming Languages/JavaScript/readme.md
  Programming Languages/Python/readme.md
Labels: gssoc, level1

#1052 DBMS - YouTube Channels and YouTube Playlist
  DBMS (Database)/readme.md
Labels: gssoc, level1

#1053 Add Chess in frontend projects
  Web Development/Frontend Development/readme.md
Labels: gssoc, level1

#1054 added dsa interview questions
  Data Structures and Algorithm (DSA)/readme.md
Labels: gssoc, level1

#1025 Machine Learning - Added "Machine Learning Courses"
  Machine learning/readme.md
Labels: gssoc, level1

#1059 added dbms playlist
  DBMS (Database)/readme.md
Labels: gssoc, level1

#1037 Added "JQuery" Complete Resources
  Programming Languages/JQuery/readme.md
Labels: gssoc, level3

#1109 Added New Java Project
  Programming Languages/Java/readme.md
Labels: gssoc, level1

#930 DSA implemations of several Programming languages
  Data Structures and Algorithm (DSA)/readme.md
Labels: gssoc, level2

#1090 Added Data science resource
  Data Science/readme.md
Labels: gssoc, level1

#1091 Added App development resource
  App Development/readme.md
Labels: gssoc, level1

#1098 Added SQL Cheatsheets section
  Programming Languages/SQL/readme.md
Labels: gssoc, level1

#1039 Programming Languages - "Bash" Complete Resources
  Programming Languages/Bash/Readme.md
Labels: gssoc, level2

#1113 Added New Java project
  Programming Languages/Java/readme.md
Labels: gssoc, level1

#1116 Added Projects in computer networks
  Computer Networks/readme.md
Labels: gssoc, level1

#1110 DBMS (Database) - Added "MySQL" Resources
  DBMS (Database)/DBMS Overview/readme.md
  DBMS (Database)/MySQL/readme.md
Labels: gssoc, level3

#1086 Next js - Complete resources
  Programming Languages/Next JS/readme.md
Labels: gssoc, level3

#1124 added youtube channel for DSA concepts
  Data Structures and Algorithm (DSA)/readme.md
Labels: gssoc, level1

#1125 Added New Resource
  Computer Architecture/README.md
Labels: gssoc, level3

#1130 Added backend api to fetch resourse and also added display contant page
  new-website/Resourse.js
  new-website/assets/logo.png
  new-website/content-display.html
  new-website/index.html
  new-website/mainstyle.css
  new-website/style.css
Labels: gssoc, level3

#416 deployment added
  Web Development/Full stack Development/readme.md
Labels: gssoc, level2

#1137 added ml projects
  Machine learning/readme.md
Labels: gssoc, level1

#1119 Added Competitive Programming Roadmap
  Data Structures and Algorithm (DSA)/Competitive Programming/readme.md
  README.md
Labels: gssoc, level3

#1122 Added Footer
  new-website/assets/footerDark.png
  new-website/assets/footerLight.png
  new-website/home.js
  new-website/index.html
  new-website/style.css
Labels: gssoc, level2

#1141 Made changes the social icons, toggle placements, particles and font
  new-website/assets/homeparticles.json
  new-website/index.html
  new-website/style.css
Labels: gssoc, level1

#1143 test preview
  .github/workflows/preview.yaml
  .github/workflows/production.yaml
Labels: gssoc

#1148 Added skeleton loading animation to resourse card
  new-website/Resourse.js
  new-website/index.html
  new-website/loading.css
  new-website/style.css
Labels: gssoc, level2

#1139 PR no - #1111 --> [RESOURCE] - Modules/Libraries of Machine Learning Section and Machine Learning Algorithms
  Machine learning/readme.md
Labels: gssoc, level1

#1149 test auto-label
  .github/workflows/auto-label.yml
Labels: gssoc

#1151 added a resource in python
  Programming Languages/Python/readme.md
Labels: gssoc, level1

#1089 Two-extensions added
  Web Development/Frontend Development/readme.md
Labels: gssoc, level1

#1085 Add Complete MongoDB resources
  DBMS (Database)/MongoDB/readme.md
Labels: gssoc, level3

#1080 ReactJS updated+grammartical errors
  Programming Languages/React JS/readme.md
Labels: gssoc, level1

#1153 Programming Languages - "Django" Complete Resources
  Programming Languages/Django/readme.md
Labels: gssoc, level3

#1161 added OS playlist
  Operating System (OS)/readme.md
Labels: gssoc, level1

#1162 Added youtube channel in DSA
  Data Structures and Algorithm (DSA)/readme.md
Labels: gssoc, level1

#1070 Prolog Formatting done
  Programming Languages/Prolog/readme.md
Labels: gssoc, level1

#1170 Clojure formatting done
  Programming Languages/Clojure/readme.md
Labels: gssoc, level1

#1169 lisp formatting done
  Programming Languages/Lisp/readme.md
Labels: gssoc, level1

#1177 DBMS - Online code editors
  DBMS (Database)/readme.md
Labels: gssoc, level1

#1131 Programming Languages - Added "GraphQL" Complete Resources
  DBMS (Database)/GraphQL/readme.md
Labels: gssoc, level3

#1150 added Data Science Interview Questions
  Data Science/readme.md
Labels: gssoc, level1

#1188 Added roadmap for DSA
  Data Structures and Algorithm (DSA)/readme.md
Labels: gssoc, level1

#1189 Added Data Structures and Algorithms - Full Course in C++
  Data Structures and Algorithm (DSA)/readme.md
Labels: gssoc, level1

#1190 added project in frontend development
  Web Development/Frontend Development/readme.md
Labels: gssoc, level1

#1191 Cyber Security - YouTube resources
  Cybersecurity/readme.md
Labels: gssoc, level1

#1193 added favicon
  Error.html
  new-website/content-display.html
  new-website/index.html
Labels: gssoc, level1

#1194 added roadmap section in open source development
  Open Source Development/readme.md
Labels: gssoc, level1

#1197 Added resource of gym website
  Web Development/Frontend Development/readme.md
Labels: gssoc, level1

#1206 Made organizaion responsive in nav bar
  new-website/index.html
Labels: gssoc, level1

#1203 Added C++ Youtube Playlist
  Programming Languages/C++/readme.md
Labels: gssoc, level1

#1202 Added Online C++ Compiler
  Programming Languages/C++/readme.md
Labels: gssoc, level1

#1201 Added OS Playlist
  Operating System (OS)/readme.md
Labels: gssoc, level1

#1211 added Cybersecurity Youtube playlist
  Cybersecurity/readme.md
Labels: gssoc, level1
